In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/listing_sample.csv")

print(df.shape)
df.head()

(1000, 7)

,L_ListingID,L_Address,L_City,beds,baths,price,remarks
0,1189451542,36612 Desert Tortoise Road,Murrieta,3.0,3.0,635000,"Welcome to 36612 Desert Tortoise Road, a beaut..."
1,1159634800,904 Amistad Court C,El Cajon,2.0,2.0,409000,PRICE REDUCED! on this IMMACULATE turnkey cond...
2,1144651476,1255 Delresto Drive,Beverly Hills,4.0,4.0,14495000,"Majestic Gated Italian Villa, An Architectural..."
3,1179077960,16855 Redwood Lodge Road,Los Gatos,4.0,3.0,1195000,Tucked into the trees of the Santa Cruz Mounta...
4,1190215696,5252 Agnes 2,Valley Village,2.0,2.0,599000,A magnificently remodeled corner unis with 3 (...

In [2]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nMissing values:")
print(df.isnull().sum())

print("\nNumeric summary:")
display(df[["beds", "baths", "price"]].describe())

Shape: (1000, 7)

Columns:
['L_ListingID', 'L_Address', 'L_City', 'beds', 'baths', 'price', 'remarks']

Missing values:
L_ListingID    0
L_Address      3
L_City         0
beds           1
baths          1
price          0
remarks        0
dtype: int64

Numeric summary:

             beds       baths         price
count  999.000000  999.000000  1.000000e+03
mean     3.361361    2.853854  1.519422e+06
std      1.412281    1.513024  2.721485e+06
min      0.000000    0.000000  1.500000e+04
25%      2.000000    2.000000  5.599750e+05
50%      3.000000    3.000000  8.170000e+05
75%      4.000000    3.000000  1.399000e+06
max     12.000000   16.000000  4.500000e+07

remarks: the listing description written by the agent. contains the natural-language text we’re going to analyze

In [3]:
df["remark_length"] = df["remarks"].str.len()

print(df["remark_length"].describe())

df[["remarks", "remark_length"]].head()

count    1000.000000
mean     1326.651000
std       574.222949
min        60.000000
25%       899.250000
50%      1281.000000
75%      1684.000000
max      3257.000000
Name: remark_length, dtype: float64

                                             remarks  remark_length
0  Welcome to 36612 Desert Tortoise Road, a beaut...           1719
1  PRICE REDUCED! on this IMMACULATE turnkey cond...            506
2  Majestic Gated Italian Villa, An Architectural...           2522
3  Tucked into the trees of the Santa Cruz Mounta...            808
4  A magnificently remodeled corner unis with 3 (...           1073

In [4]:
df["L_City"].value_counts().head(15)

L_City
Los Angeles         74
San Diego           37
Palm Springs        16
Temecula            14
Riverside           13
Irvine              13
San Jose            12
Palm Desert         12
Murrieta            11
Hemet               11
Rancho Cucamonga    11
Corona              11
Long Beach          10
Huntington Beach     9
Palmdale             8
Name: count, dtype: int64

## Common Word Analysis

To better understand the language used in real estate listing remarks, the text is converted to lowercase and tokenized into individual words. Common English stopwords such as "the", "and", and "is" are removed, along with punctuation and non-alphabetic tokens.

The remaining words are counted to identify the most frequently used real estate terms in the sample dataset.

In [5]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from collections import Counter

nltk.download("punkt")
nltk.download("stopwords")

stop_words = set(stopwords.words("english"))

all_text = " ".join(df["remarks"].dropna().str.lower())

tokens = word_tokenize(all_text)

filtered_tokens = [
    word for word in tokens
    if word.isalpha() and word not in stop_words
]

word_freq = Counter(filtered_tokens)

word_freq.most_common(30)

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/nghi_nguyen/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/nghi_nguyen/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

[('home', 2451),
 ('living', 1869),
 ('room', 1371),
 ('space', 1116),
 ('offers', 1078),
 ('kitchen', 965),
 ('private', 884),
 ('dining', 795),
 ('features', 789),
 ('area', 721),
 ('property', 713),
 ('spacious', 679),
 ('bedrooms', 671),
 ('located', 619),
 ('access', 609),
 ('new', 573),
 ('garage', 569),
 ('community', 565),
 ('entertaining', 559),
 ('enjoy', 555),
 ('bedroom', 548),
 ('additional', 527),
 ('views', 522),
 ('one', 515),
 ('perfect', 482),
 ('primary', 481),
 ('large', 481),
 ('bathroom', 479),
 ('opportunity', 464),
 ('family', 460)]

## Bigram Analysis

Single words can miss important real estate concepts that are usually expressed as two-word phrases. Bigrams are pairs of consecutive words, such as "open floor", "floor plan", or "gated community".

The most frequent bigrams are extracted from the cleaned listing remarks to help identify candidate phrases for the Week 1 real estate taxonomy.

In [6]:
from nltk.util import ngrams

bigrams = list(ngrams(filtered_tokens, 2))

bigram_freq = Counter(bigrams)

bigram_freq.most_common(30)

[(('floor', 'plan'), 323),
 (('living', 'room'), 313),
 (('home', 'offers'), 303),
 (('primary', 'suite'), 290),
 (('living', 'space'), 278),
 (('natural', 'light'), 262),
 (('dining', 'area'), 189),
 (('home', 'office'), 177),
 (('square', 'feet'), 176),
 (('family', 'room'), 176),
 (('stainless', 'steel'), 172),
 (('everyday', 'living'), 171),
 (('shopping', 'dining'), 168),
 (('conveniently', 'located'), 162),
 (('steel', 'appliances'), 150),
 (('home', 'features'), 145),
 (('located', 'near'), 142),
 (('laundry', 'room'), 136),
 (('pool', 'spa'), 132),
 (('thoughtfully', 'designed'), 125),
 (('easy', 'access'), 125),
 (('bedrooms', 'bathrooms'), 122),
 (('living', 'area'), 120),
 (('living', 'spaces'), 119),
 (('living', 'entertaining'), 116),
 (('rare', 'opportunity'), 115),
 (('attached', 'garage'), 113),
 (('sq', 'ft'), 108),
 (('dining', 'room'), 105),
 (('living', 'dining'), 102)]

## Extended Bigram Review

To build a broader real estate taxonomy, the most frequent bigrams are expanded beyond the top 30. This provides a larger set of candidate phrases that can be reviewed and grouped into meaningful real estate categories.

In [7]:
top_bigrams = [
    (" ".join(pair), count)
    for pair, count in bigram_freq.most_common(150)
]

top_bigrams[:150]

[('floor plan', 323),
 ('living room', 313),
 ('home offers', 303),
 ('primary suite', 290),
 ('living space', 278),
 ('natural light', 262),
 ('dining area', 189),
 ('home office', 177),
 ('square feet', 176),
 ('family room', 176),
 ('stainless steel', 172),
 ('everyday living', 171),
 ('shopping dining', 168),
 ('conveniently located', 162),
 ('steel appliances', 150),
 ('home features', 145),
 ('located near', 142),
 ('laundry room', 136),
 ('pool spa', 132),
 ('thoughtfully designed', 125),
 ('easy access', 125),
 ('bedrooms bathrooms', 122),
 ('living area', 120),
 ('living spaces', 119),
 ('living entertaining', 116),
 ('rare opportunity', 115),
 ('attached garage', 113),
 ('sq ft', 108),
 ('dining room', 105),
 ('living dining', 102),
 ('step outside', 101),
 ('granite countertops', 100),
 ('quartz countertops', 97),
 ('property offers', 96),
 ('kitchen features', 95),
 ('recessed lighting', 95),
 ('covered patio', 92),
 ('full bathroom', 90),
 ('soaking tub', 89),
 ('generously sized', 87),
 ('spacious primary', 85),
 ('beautifully maintained', 83),
 ('beautifully updated', 82),
 ('plenty room', 82),
 ('throughout home', 81),
 ('ideally located', 81),
 ('approximately square', 80),
 ('spacious living', 80),
 ('main level', 79),
 ('primary bedroom', 79),
 ('vaulted ceilings', 79),
 ('great room', 78),
 ('car garage', 78),
 ('offers perfect', 77),
 ('outdoor living', 77),
 ('morning coffee', 76),
 ('additional bedrooms', 76),
 ('highlights include', 76),
 ('water heater', 75),
 ('living areas', 75),
 ('perfect blend', 73),
 ('mountain views', 73),
 ('amenities including', 72),
 ('highly desirable', 72),
 ('comfortable living', 71),
 ('residence offers', 70),
 ('additional highlights', 70),
 ('abundant natural', 70),
 ('step inside', 69),
 ('chef kitchen', 69),
 ('southern california', 69),
 ('formal dining', 68),
 ('los angeles', 68),
 ('convenient access', 67),
 ('direct access', 66),
 ('open floor', 66),
 ('private backyard', 66),
 ('comfort convenience', 66),
 ('full bath', 65),
 ('ceiling fans', 64),
 ('golf course', 64),
 ('updated kitchen', 62),
 ('features include', 61),
 ('main living', 61),
 ('private balcony', 60),
 ('washer dryer', 60),
 ('air conditioning', 59),
 ('fitness center', 59),
 ('bedroom bath', 59),
 ('sliding glass', 58),
 ('bonus room', 58),
 ('private retreat', 58),
 ('filled natural', 58),
 ('located within', 57),
 ('bedroom bathroom', 57),
 ('suite offers', 57),
 ('relaxing entertaining', 56),
 ('family guests', 56),
 ('remodeled kitchen', 56),
 ('offers exceptional', 56),
 ('bedroom full', 56),
 ('soaring ceilings', 56),
 ('hardwood floors', 55),
 ('flows seamlessly', 54),
 ('freeway access', 54),
 ('custom cabinetry', 53),
 ('center island', 53),
 ('community amenities', 53),
 ('extended family', 53),
 ('home located', 53),
 ('outdoor space', 52),
 ('walking distance', 52),
 ('heart home', 52),
 ('welcome beautifully', 52),
 ('school district', 51),
 ('bedrooms full', 51),
 ('fresh interior', 51),
 ('flooring throughout', 51),
 ('spacious bedrooms', 51),
 ('two additional', 51),
 ('room fireplace', 50),
 ('residents enjoy', 50),
 ('gated community', 49),
 ('cozy fireplace', 49),
 ('full bathrooms', 49),
 ('major freeways', 49),
 ('palm springs', 49),
 ('formal living', 48),
 ('blend comfort', 47),
 ('interior paint', 47),
 ('beautifully remodeled', 46),
 ('outdoor dining', 46),
 ('home also', 46),
 ('high ceilings', 46),
 ('detached garage', 46),
 ('tile flooring', 45),
 ('dual vanities', 45),
 ('endless possibilities', 45),
 ('laminate flooring', 45),
 ('fruit trees', 45),
 ('room features', 45),
 ('guests home', 45),
 ('solar panels', 45),
 ('dining areas', 45),
 ('glass doors', 44),
 ('home offering', 44),
 ('peace mind', 44),
 ('sparkling pool', 44),
 ('owned solar', 44),
 ('dual sinks', 44)]

## Taxonomy Candidate Exploration

The most frequent words and bigrams contain both useful real estate concepts and generic marketing language. To support taxonomy construction, candidate terms are grouped using real estate-related keywords.

These candidate groups will be manually reviewed before creating the final taxonomy.

In [8]:
# Combine frequent unigrams and bigrams into candidate terms
unigram_candidates = [
    (word, count)
    for word, count in word_freq.most_common(300)
]

bigram_candidates = [
    (" ".join(pair), count)
    for pair, count in bigram_freq.most_common(500)
]

all_candidates = unigram_candidates + bigram_candidates


category_keywords = {
    "rooms_spaces": [
        "room", "bedroom", "bathroom", "suite", "office",
        "kitchen", "dining", "laundry", "loft", "den"
    ],

    "kitchen_appliances": [
        "kitchen", "appliance", "stainless", "oven", "refrigerator",
        "dishwasher", "countertop", "cabinet", "island"
    ],

    "property_features": [
        "floor", "garage", "fireplace", "closet", "storage",
        "light", "window", "ceiling", "solar"
    ],

    "amenities": [
        "pool", "spa", "gym", "clubhouse", "community",
        "tennis", "security", "gated"
    ],

    "outdoor_features": [
        "yard", "patio", "balcony", "deck", "garden",
        "landscape", "lot", "outdoor"
    ],

    "location_access": [
        "school", "shopping", "dining", "freeway", "access",
        "near", "located", "park", "beach"
    ],

    "condition_style": [
        "new", "updated", "remodeled", "renovated", "modern",
        "luxury", "custom", "design"
    ],

    "measurements_financial": [
        "square", "sq", "feet", "acre", "price",
        "finance", "hoa", "solar"
    ]
}


taxonomy_candidates = {}

for category, keywords in category_keywords.items():
    matches = []

    for term, count in all_candidates:
        if any(keyword in term for keyword in keywords):
            matches.append((term, count))

    # Remove duplicates while keeping frequency order
    seen = set()
    unique_matches = []

    for term, count in sorted(matches, key=lambda x: x[1], reverse=True):
        if term not in seen:
            unique_matches.append((term, count))
            seen.add(term)

    taxonomy_candidates[category] = unique_matches[:40]


for category, terms in taxonomy_candidates.items():
    print(f"\n--- {category.upper()} ---")
    for term, count in terms:
        print(f"{term}: {count}")

--- ROOMS_SPACES ---
room: 1371
kitchen: 965
dining: 795
bedrooms: 671
bedroom: 548
bathroom: 479
residence: 437
suite: 409
bathrooms: 358
office: 322
living room: 313
primary suite: 290
laundry: 285
dining area: 189
home office: 177
family room: 176
shopping dining: 168
laundry room: 136
bedrooms bathrooms: 122
dining room: 105
living dining: 102
garden: 98
kitchen features: 95
full bathroom: 90
plenty room: 82
primary bedroom: 79
great room: 78
additional bedrooms: 76
residence offers: 70
chef kitchen: 69
formal dining: 68
updated kitchen: 62
bedroom bath: 59
bonus room: 58
bedroom bathroom: 57
suite offers: 57
remodeled kitchen: 56
bedroom full: 56
bedrooms full: 51
spacious bedrooms: 51

--- KITCHEN_APPLIANCES ---
kitchen: 965
appliances: 326
cabinetry: 288
countertops: 267
stainless: 188
stainless steel: 172
island: 169
steel appliances: 150
granite countertops: 100
cabinets: 98
quartz countertops: 97
kitchen features: 95
chef kitchen: 69
updated kitchen: 62
remodeled kitchen: 56
custom cabinetry: 53
center island: 53
countertops stainless: 43
kitchen dining: 42
kitchen featuring: 40
kitchen offers: 37
white cabinetry: 35
gourmet kitchen: 34
abundant cabinetry: 33
room kitchen: 29
open kitchen: 28
kitchen living: 27
spacious kitchen: 26
area kitchen: 25
outdoor kitchen: 25
appliances including: 21
cabinetry granite: 19

--- PROPERTY_FEATURES ---
garage: 569
floor: 457
storage: 431
flooring: 369
fireplace: 363
light: 350
floor plan: 323
closet: 320
windows: 285
ceilings: 279
natural light: 262
lighting: 202
solar: 188
ceiling: 149
floors: 129
attached garage: 113
closets: 108
recessed lighting: 95
vaulted ceilings: 79
car garage: 78
highlights include: 76
additional highlights: 70
open floor: 66
ceiling fans: 64
soaring ceilings: 56
hardwood floors: 55
flooring throughout: 51
room fireplace: 50
cozy fireplace: 49
high ceilings: 46
detached garage: 46
tile flooring: 45
laminate flooring: 45
solar panels: 45
owned solar: 44
solar system: 41
wood flooring: 41
additional storage: 41
gas fireplace: 39
storage space: 36

--- AMENITIES ---
space: 1116
spacious: 679
community: 565
pool: 421
spaces: 300
living space: 278
spa: 218
gated: 199
pool spa: 132
living spaces: 119
tennis: 103
spacious primary: 85
spacious living: 80
community amenities: 53
outdoor space: 52
spacious bedrooms: 51
gated community: 49
sparkling pool: 44
counter space: 43
tennis courts: 41
parking spaces: 38
storage space: 36
plenty space: 35
swimming pool: 34
community pool: 33
features spacious: 31
spacious home: 29
space home: 27
spacious kitchen: 26
closet space: 26
parking space: 23
outdoor spaces: 23
open space: 21
ample space: 19

--- OUTDOOR_FEATURES ---
outdoor: 451
backyard: 386
lot: 307
patio: 284
yard: 176
deck: 159
balcony: 145
garden: 98
covered patio: 92
outdoor living: 77
private backyard: 66
private balcony: 60
outdoor space: 52
outdoor dining: 46
corner lot: 39
front yard: 39
private patio: 32
back yard: 31
indoor outdoor: 31
beautifully landscaped: 31
outdoor entertaining: 29
private outdoor: 28
outdoor kitchen: 25
sq lot: 23
outdoor spaces: 23
landscaped grounds: 21
side yard: 21
backyard oasis: 20
outdoor retreat: 20
large backyard: 19

--- LOCATION_ACCESS ---
dining: 795
located: 619
access: 609
shopping: 398
parking: 305
near: 227
park: 224
schools: 206
parks: 196
dining area: 189
shopping dining: 168
conveniently located: 162
located near: 142
beach: 138
school: 131
easy access: 125
freeways: 120
dining room: 105
living dining: 102
nearby: 96
ideally located: 81
formal dining: 68
convenient access: 67
direct access: 66
located within: 57
freeway access: 54
home located: 53
school district: 51
major freeways: 49
outdoor dining: 46
dining areas: 45
sparkling pool: 44
kitchen dining: 42
near shopping: 39
parking spaces: 38
dining shopping: 37
room dining: 35
located minutes: 35
schools shopping: 34
guest parking: 33

--- CONDITION_STYLE ---
new: 573
designed: 429
updated: 383
modern: 380
custom: 339
remodeled: 231
luxury: 196
newer: 158
design: 152
thoughtfully designed: 125
beautifully updated: 82
updated kitchen: 62
remodeled kitchen: 56
custom cabinetry: 53
beautifully remodeled: 46
brand new: 43
designed living: 39
modern living: 39
designed everyday: 36
luxury vinyl: 34
new construction: 33
new flooring: 33
modern comfort: 32
thoughtfully updated: 31
designed floor: 29
updated home: 28
include new: 28
new roof: 24
designed entertaining: 24
beautifully designed: 22
modern finishes: 21
designed comfort: 21
modern updates: 21
modern design: 21
updated bathrooms: 20
designer finishes: 20
plan designed: 20

--- MEASUREMENTS_FINANCIAL ---
square: 242
sq: 215
solar: 188
feet: 187
square feet: 176
hoa: 117
sq ft: 108
acres: 95
approximately square: 80
solar panels: 45
owned solar: 44
solar system: 41
feet living: 35
square foot: 35
approximately sq: 35
low hoa: 29
paid solar: 29
feet thoughtfully: 28
hoa dues: 25
sq lot: 23
offers square: 20